services:
  ddns:
    container_name: ddns
    build: .
    image: ddns:latest
    environment:
      ZONE_ID: ${ZONE_ID}
      DNS_RECORD_ID: ${DNS_RECORD_ID}
      CLOUDFLARE_API_KEY: ${CLOUDFLARE_API_KEY}
    command: ["/app/init.sh"]
    restart: unless-stopped
